language: python
python:
    - "3.7.3"
install: "pip install -r requirements.txt"
script:
    - SECRET_KEY="" ./manage.py test
env:
    - MYSQL_USERNAME=root MYSQL_DATABASENAME="" MYSQL_PASSWORD="" MYSQL_HOST=127.0.0.1
notifications:
  email: false