# Generated by Django 2.2.3 on 2019-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0004_auto_20190806_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antique',
            old_name='Title',
            new_name='Antique',
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
    ]
