# Generated by Django 2.2.3 on 2019-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0005_auto_20190806_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antique',
            old_name='Antique',
            new_name='AntiqueName',
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
    ]
