# Generated by Django 2.2.3 on 2019-08-09 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0006_auto_20190807_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
        migrations.CreateModel(
            name='AntiqueSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular antique across the whole site', primary_key=True, serialize=False)),
                ('customerFirstName', models.CharField(max_length=100)),
                ('customerLastName', models.CharField(max_length=100)),
                ('customerAddressLine1', models.TextField(max_length=200)),
                ('customerAddressLine2', models.TextField(max_length=200, null=True)),
                ('customerAddressCity', models.TextField(max_length=200)),
                ('customerAddressCounty', models.TextField(max_length=200)),
                ('customerAddressPostcode', models.TextField(max_length=12)),
                ('customerEmail', models.TextField(max_length=200)),
                ('customerTelephone', models.TextField(max_length=20)),
                ('antique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiqueProjectApp.Antique')),
            ],
        ),
    ]
