# Generated by Django 2.2.3 on 2019-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0007_auto_20190809_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiquesale',
            old_name='antique',
            new_name='antiqueBuyer',
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
    ]
