# Generated by Django 2.2.3 on 2019-08-12 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0009_auto_20190812_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiquesale',
            name='antique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiqueProjectApp.Antique'),
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
        migrations.AlterField(
            model_name='antiquesale',
            name='antiqueBuyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='antiquesale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular antique sale', primary_key=True, serialize=False),
        ),
    ]
