# Generated by Django 2.2.3 on 2019-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0011_auto_20190812_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiquesale',
            options={'permissions': (('can_buy', 'Set antique as purchased'),)},
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
    ]
