# Generated by Django 2.2.3 on 2019-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0012_auto_20190812_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiquesale',
            options={},
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
    ]
