# Generated by Django 2.2.4 on 2019-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueProjectApp', '0014_auto_20190814_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='AntiqueImage',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='antique',
            name='AntiqueType',
            field=models.ManyToManyField(help_text='Select a type for this antique', to='antiqueProjectApp.AntiqueType'),
        ),
        migrations.AlterField(
            model_name='antique',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
